sudo: required

dist: focal

services:
  - docker

before_script:
  - mkdir -p ~/.docker/cli-plugins
  - wget -O - https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name mybuilder


script:
  - echo "Build local image"
  - docker login -u subham328 -p Ak@sh328
  - docker buildx build --platform linux/amd64,linux/arm64 -t subham328/file-beat:1.1 --push .
  - docker images
  - echo "Run local image"
  - docker run -d --name filebeat filebeat
  - docker ps -a
  - docker logs filebeat
  - echo "Testing public image on Docker Hub"
  - docker run -d --name nguoianphu-filebeat nguoianphu/docker-filebeat
  - docker ps -a
  - docker logs nguoianphu-filebeat  
  - docker images

